### ISSUE TITLE
v2: move `platform.ini` to root

### ISSUE THREAD

**Issue by puzrin** [manuelbl/usb-pd-arduino#14]
This should simplify development. Now I need to add `dev/` as a separate project to PIO workspace and have issues with Intellisense.

Such config is used only by "application" and should not conflict with the library.

If you have no objections, I will do an update.

**Comment by manuelbl** [comment]
If you have a good setup that works with PlatformIO, then go ahead. You probably don't want to move an existing `platformio.ini` file but rather add a new one. Or which one would you move?

**Comment by puzrin** [comment]
Ah, you are right. Then i suggest create the merge of those 2 files in the root:

- https://github.com/manuelbl/usb-pd-arduino/blob/v2/dev/VoltageChange/platformio.ini
- https://github.com/manuelbl/usb-pd-arduino/blob/v2/dev/ListCapabilities/platformio.ini

That will be enough for development, and what to do with old files - can be decided later.

Ok?
